# Generated by Django 5.2.5 on 2025-08-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="sobrenome",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Sobrenome"
            ),
        ),
    ]
