# Generated by Django 5.2.5 on 2025-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0002_perfil_sobrenome"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto de perfil a ser exibida para todos os usuários ",
                null=True,
                upload_to="perfil/fotos/%Y/%m/%d",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
