# Generated by Django 5.2.5 on 2025-08-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0003_perfil_foto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil",
            old_name="usuario",
            new_name="user",
        ),
    ]
