# Generated by Django 5.2.5 on 2025-09-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0004_rename_usuario_perfil_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerguntasDoUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Javascript", "Javascript"),
                            ("Python", "Python"),
                            ("C#", "C#"),
                            ("HTML", "HTML"),
                            ("CSS", "CSS"),
                            ("Java", "Java"),
                            ("PHP", "PHP"),
                            ("C++", "C++"),
                            ("SQL", "SQL"),
                            ("Shell", "Shell"),
                            ("PowerShell", "PowerShell"),
                            ("Git", "Git"),
                            ("React", "React"),
                            ("Angular", "Angular"),
                            ("Vue", "Vue"),
                            ("NodeJS", "NodeJS"),
                            ("Express", "Express"),
                            ("MongoDB", "MongoDB"),
                            ("MySQL", "MySQL"),
                            ("PostgreSQL", "PostgreSQL"),
                            ("Firebase", "Firebase"),
                            ("AWS", "AWS"),
                            ("Azure", "Azure"),
                            ("Docker", "Docker"),
                            ("Kubernetes", "Kubernetes"),
                            ("Terraform", "Terraform"),
                            ("Ansible", "Ansible"),
                            ("Linux", "Linux"),
                            ("Windows", "Windows"),
                            ("MacOS", "MacOS"),
                            ("iOS", "iOS"),
                            ("Android", "Android"),
                            ("Flutter", "Flutter"),
                            ("Unity", "Unity"),
                            ("Unreal", "Unreal"),
                            ("Godot", "Godot"),
                            ("Blender", "Blender"),
                            ("Photoshop", "Photoshop"),
                            ("Illustrator", "Illustrator"),
                            ("Inkscape", "Inkscape"),
                            ("Figma", "Figma"),
                            ("Sketch", "Sketch"),
                            ("WebGL", "WebGL"),
                            ("ThreeJS", "ThreeJS"),
                            ("OpenGL", "OpenGL"),
                            ("DirectX", "DirectX"),
                            ("Vulkan", "Vulkan"),
                            ("AR", "AR"),
                            ("VR", "VR"),
                            ("XR", "XR"),
                            ("AI", "AI"),
                            ("ML", "ML"),
                            ("DL", "DL"),
                            ("IOT", "IOT"),
                            ("Blockchain", "Blockchain"),
                            ("Crypto", "Crypto"),
                            ("Blockchain", "Blockchain"),
                            ("Rust", "Rust"),
                            ("Go", "Go"),
                            ("Dart", "Dart"),
                            ("Kotlin", "Kotlin"),
                            ("Swift", "Swift"),
                            ("Objective-C", "Objective-C"),
                        ],
                        default=None,
                        help_text="Categoria do post",
                        null=True,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta",
                "verbose_name_plural": "Perguntas",
            },
        ),
        migrations.CreateModel(
            name="FotoErro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        upload_to="erros/fotos/%Y/%m/%d", verbose_name="Fotos do erro"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="perfil.perguntasdousuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto de Erro",
                "verbose_name_plural": "Fotos de Erro",
            },
        ),
    ]
