# Generated by Django 5.2.5 on 2025-09-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0006_votos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="votos",
            old_name="valor",
            new_name="avaliacao",
        ),
    ]
