# Generated by Django 5.2.5 on 2025-09-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0009_respostasdousuario_imagem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostasdousuario",
            name="avaliacao",
            field=models.SmallIntegerField(
                blank=True, choices=[(1, "Like"), (-1, "Dislike")], null=True
            ),
        ),
    ]
