# Generated by Django 5.2.5 on 2025-09-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0011_alter_respostasdousuario_avaliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostasdousuario",
            name="resposta",
            field=models.TextField(blank=True, null=True),
        ),
    ]
