# Generated by Django 5.2.5 on 2025-09-23 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0012_alter_respostasdousuario_resposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostasdousuario",
            name="data_de_criacao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
