# Generated by Django 5.2.5 on 2025-09-24 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0013_respostasdousuario_data_de_criacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="respostasdousuario",
            options={
                "ordering": ["-data_de_criacao"],
                "verbose_name": "Resposta",
                "verbose_name_plural": "Respostas",
            },
        ),
        migrations.RemoveField(
            model_name="respostasdousuario",
            name="avaliacao",
        ),
        migrations.CreateModel(
            name="AvaliacaoResposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_avaliacao",
                    models.SmallIntegerField(
                        choices=[(1, "Like"), (-1, "Dislike")],
                        verbose_name="Tipo de Avaliação",
                    ),
                ),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="perfil.respostasdousuario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Resposta",
                "verbose_name_plural": "Avaliações de Respostas",
                "unique_together": {("usuario", "resposta")},
            },
        ),
    ]
