# Generated by Django 5.2.5 on 2025-09-25 00:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0014_alter_respostasdousuario_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaDaResposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_de_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        help_text="Foto de resposta a ser exibida para todos os usuários ",
                        null=True,
                        upload_to="respostas/fotos/%Y/%m/%d",
                        verbose_name="Foto de resposta",
                    ),
                ),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resposta_da_resposta",
                        to="perfil.respostasdousuario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resposta_da_resposta_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta da Resposta",
                "verbose_name_plural": "Respostas da Resposta",
                "ordering": ["-data_de_criacao"],
                "unique_together": {("usuario", "resposta")},
            },
        ),
    ]
