# Generated by Django 5.2.5 on 2025-09-26 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0015_respostadaresposta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvaliacaoRespostaDaResposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_avaliacao",
                    models.SmallIntegerField(
                        choices=[(1, "Like"), (-1, "Dislike")],
                        verbose_name="Tipo de Avaliação",
                    ),
                ),
                ("data_avaliacao", models.DateTimeField(auto_now_add=True)),
                (
                    "resposta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resposta_da_resposta",
                        to="perfil.respostadaresposta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_avaliacao_resposta_da_resposta",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação de Resposta da Resposta",
                "verbose_name_plural": "Avaliações de Respostas da Resposta",
                "unique_together": {("usuario", "resposta")},
            },
        ),
    ]
