# Generated by Django 5.2.5 on 2025-10-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0016_avaliacaorespostadaresposta"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostadaresposta",
            name="texto_resposta",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="avaliacaorespostadaresposta",
            name="resposta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avaliacoes",
                to="perfil.respostadaresposta",
            ),
        ),
    ]
