# Generated by Django 5.2.5 on 2025-10-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0017_respostadaresposta_texto_resposta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perguntasdousuario",
            name="categoria",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Digite as categorias separadas por vírgula (ex: Python, Django, Web)",
                max_length=200,
                null=True,
            ),
        ),
    ]
