# Generated by Django 5.2.5 on 2025-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0017_respostadaresposta_texto_resposta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nome da Categoria"
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição opcional da categoria",
                        null=True,
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        default="#4e73df",
                        help_text="Cor em hexadecimal para exibição da categoria",
                        max_length=7,
                        verbose_name="Cor",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="fa-tag",
                        help_text="Classe do ícone FontAwesome (ex: fa-tag, fa-code, fa-database)",
                        max_length=50,
                        verbose_name="Ícone",
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(
                        default=True,
                        help_text="Se a categoria está ativa para uso",
                        verbose_name="Ativa",
                    ),
                ),
                (
                    "criada_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.RemoveField(
            model_name="perguntasdousuario",
            name="categoria",
        ),
        migrations.AddField(
            model_name="perguntasdousuario",
            name="categorias",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecione uma ou mais categorias para ajudar outros devs a encontrar sua pergunta.",
                related_name="perguntas",
                to="perfil.categoria",
                verbose_name="Categorias",
            ),
        ),
    ]
