# Generated by Django 5.2.5 on 2025-10-29 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0018_alter_perguntasdousuario_categoria"),
        ("perfil", "0018_categoria_remove_perguntasdousuario_categoria_and_more"),
    ]

    operations = []
