# Generated by Django 5.2.5 on 2025-11-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0021_notificacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificacao",
            name="resposta_da_resposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to="perfil.respostadaresposta",
            ),
        ),
        migrations.AlterField(
            model_name="notificacao",
            name="resposta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notificacoes",
                to="perfil.respostasdousuario",
            ),
        ),
        migrations.AlterField(
            model_name="respostasdousuario",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="* Foto de resposta a ser exibida para todos os usuários ",
                null=True,
                upload_to="respostas/fotos/%Y/%m/%d",
                verbose_name="Foto de resposta",
            ),
        ),
    ]
