# Generated by Django 5.2.5 on 2025-11-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0022_notificacao_resposta_da_resposta_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="respostadaresposta",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="respostadaresposta",
            name="resposta_pai",
            field=models.ForeignKey(
                blank=True,
                help_text="Resposta de resposta à qual esta resposta está respondendo",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas_filhas",
                to="perfil.respostadaresposta",
                verbose_name="Resposta Pai",
            ),
        ),
    ]
