# Generated by Django 5.2.5 on 2025-09-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lista", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotoerro",
            name="foto",
            field=models.ImageField(
                upload_to="erros/fotos/%Y/%m/%d", verbose_name="Fotos do erro"
            ),
        ),
    ]
