# Generated by Django 5.2.5 on 2025-09-06 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lista", "0002_alter_fotoerro_foto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perguntasdousuario",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="FotoErro",
        ),
        migrations.DeleteModel(
            name="PerguntasDoUsuario",
        ),
    ]
